/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sec.anchor.view;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Miyuru Madusanka
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private Date d;
    private Timer timer;
    private DateFormat timeInstance;

    public MainFrame() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        jXTaskPane1.setTitle("Employee");
        jXTaskPane2.setTitle("Salary");

        setTitle("Anchor Security Services V_1.0");
        d = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String date = dateFormat.format(d);
        dateText.setText(date);
        timeInstance = DateFormat.getTimeInstance(DateFormat.MEDIUM);

        timer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                d = new Date();
                String time = timeInstance.format(d);
                timeText.setText(time);
            }
        });
        timer.start();
        // payView();
        // paySalary.doClick();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        jXCollapsiblePane1 = new org.jdesktop.swingx.JXCollapsiblePane();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        newEmployeeButton = new javax.swing.JButton();
        updateEmployeeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        paySalary = new javax.swing.JButton();
        viewPayedButton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        employeeMenu = new javax.swing.JMenu();
        addNewEmployeeMenu = new javax.swing.JMenuItem();
        updateEmployeeMenu = new javax.swing.JMenuItem();
        removeEmployeeMenu = new javax.swing.JMenuItem();
        removeEmployeeMenu1 = new javax.swing.JMenuItem();
        salaryConfigMenu = new javax.swing.JMenu();
        paySalaryMenu = new javax.swing.JMenuItem();
        viewPayedSalaryMenu = new javax.swing.JMenuItem();
        configureSalaryMenu = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        addUserMenu = new javax.swing.JMenuItem();
        userPasswordChangeMenu = new javax.swing.JMenuItem();
        LogoutMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        backUpMenu = new javax.swing.JMenuItem();
        restoreMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 55, 55));
        jLabel1.setText("Anchor Security Services");

        jLabel2.setForeground(new java.awt.Color(171, 55, 55));
        jLabel2.setText("No 255/B, Station Road,");

        jLabel3.setForeground(new java.awt.Color(171, 55, 55));
        jLabel3.setText("Karappankadu,");

        jLabel4.setForeground(new java.awt.Color(171, 55, 55));
        jLabel4.setText("Vavuniya.");

        dateText.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        dateText.setForeground(new java.awt.Color(171, 55, 55));
        dateText.setText("date");

        timeText.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        timeText.setForeground(new java.awt.Color(171, 55, 55));
        timeText.setText("Time");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sec/anchor/images/logo_small.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(171, 55, 55));
        jLabel5.setText("0242228169");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(171, 55, 55));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>Business Reg. No.: 2972 <br>Defence Ministry Approval No.: CS/11/PS/1/1389/025/002 </html>");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sec/anchor/images/1491402370_constr_call_to_bank.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sec/anchor/images/1491402254_mail~1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(dateText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeText))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8)))))
            .addComponent(jLabel6)
        );

        dataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        jXCollapsiblePane1.setToolTipText("");

        newEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newEmployeeButton.setText("New");
        newEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeButtonActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(newEmployeeButton);

        updateEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateEmployeeButton.setText("Update");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(updateEmployeeButton);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jButton1);

        jXCollapsiblePane1.getContentPane().add(jXTaskPane1);

        paySalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paySalary.setText("Pay");
        paySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paySalaryActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(paySalary);

        viewPayedButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewPayedButton.setText("View");
        viewPayedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPayedButtonActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(viewPayedButton);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Configure");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jButton9);

        jXCollapsiblePane1.getContentPane().add(jXTaskPane2);

        jMenu5.setText("Functions");

        employeeMenu.setText("Employee");

        addNewEmployeeMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        addNewEmployeeMenu.setText("Add New");
        addNewEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmployeeMenuActionPerformed(evt);
            }
        });
        employeeMenu.add(addNewEmployeeMenu);

        updateEmployeeMenu.setText("Update");
        updateEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeMenuActionPerformed(evt);
            }
        });
        employeeMenu.add(updateEmployeeMenu);

        removeEmployeeMenu.setText("Remove");
        removeEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeMenuActionPerformed(evt);
            }
        });
        employeeMenu.add(removeEmployeeMenu);

        removeEmployeeMenu1.setText("View All");
        removeEmployeeMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeMenu1ActionPerformed(evt);
            }
        });
        employeeMenu.add(removeEmployeeMenu1);

        jMenu5.add(employeeMenu);

        salaryConfigMenu.setText("Salary");

        paySalaryMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        paySalaryMenu.setText("Pay");
        paySalaryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paySalaryMenuActionPerformed(evt);
            }
        });
        salaryConfigMenu.add(paySalaryMenu);

        viewPayedSalaryMenu.setText("View payed");
        viewPayedSalaryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPayedSalaryMenuActionPerformed(evt);
            }
        });
        salaryConfigMenu.add(viewPayedSalaryMenu);

        configureSalaryMenu.setText("Configurations");
        configureSalaryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureSalaryMenuActionPerformed(evt);
            }
        });
        salaryConfigMenu.add(configureSalaryMenu);

        jMenu5.add(salaryConfigMenu);

        jMenu10.setText("My Profile");

        addUserMenu.setText("Add Users");
        addUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserMenuActionPerformed(evt);
            }
        });
        jMenu10.add(addUserMenu);

        userPasswordChangeMenu.setText("Change Passwords");
        userPasswordChangeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordChangeMenuActionPerformed(evt);
            }
        });
        jMenu10.add(userPasswordChangeMenu);

        jMenu5.add(jMenu10);

        LogoutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        LogoutMenu.setText("Log Out");
        LogoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuActionPerformed(evt);
            }
        });
        jMenu5.add(LogoutMenu);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Reports");

        jMenuItem14.setText("Total Payments");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Bank Reports");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("EPF Reports");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuItem17.setText("View All Employees");
        jMenu4.add(jMenuItem17);

        jMenuBar1.add(jMenu4);

        jMenu12.setText("Database");

        backUpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        backUpMenu.setText("Backup");
        backUpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUpMenuActionPerformed(evt);
            }
        });
        jMenu12.add(backUpMenu);

        restoreMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        restoreMenu.setText("Restore");
        restoreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreMenuActionPerformed(evt);
            }
        });
        jMenu12.add(restoreMenu);

        jMenuBar1.add(jMenu12);

        jMenu3.setText("Help");

        jMenuItem1.setText("Help Window");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("About");

        jMenuItem18.setText("Developer Team");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXCollapsiblePane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXCollapsiblePane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeButtonActionPerformed
        AddEmployee addEmployee = new AddEmployee();
        System.gc();
        addEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(addEmployee);
        dataPanel.repaint();

    }//GEN-LAST:event_newEmployeeButtonActionPerformed

    private void viewPayedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPayedButtonActionPerformed
        PayedSalary payedSalary = new PayedSalary();
        System.gc();
        payedSalary.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(payedSalary);
        dataPanel.repaint();
    }//GEN-LAST:event_viewPayedButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        UpdateEmployee updateEmployee = new UpdateEmployee();
        System.gc();
        updateEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(updateEmployee);
        dataPanel.repaint();
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void paySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paySalaryActionPerformed
        payView();
    }//GEN-LAST:event_paySalaryActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ConfigureSalary configureSalary = new ConfigureSalary();
        System.gc();
        System.gc();
        configureSalary.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(configureSalary);
        dataPanel.repaint();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void backUpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUpMenuActionPerformed
        new BackupRestore(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_backUpMenuActionPerformed

    private void addNewEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEmployeeMenuActionPerformed
        AddEmployee addEmployee = new AddEmployee();
        System.gc();
        addEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(addEmployee);
        dataPanel.repaint();
    }//GEN-LAST:event_addNewEmployeeMenuActionPerformed

    private void updateEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeMenuActionPerformed
        UpdateEmployee updateEmployee = new UpdateEmployee();
        System.gc();
        updateEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(updateEmployee);
        dataPanel.repaint();
    }//GEN-LAST:event_updateEmployeeMenuActionPerformed

    private void removeEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeMenuActionPerformed
        UpdateEmployee updateEmployee = new UpdateEmployee();
        System.gc();
        updateEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(updateEmployee);
        dataPanel.repaint();
    }//GEN-LAST:event_removeEmployeeMenuActionPerformed

    private void LogoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuActionPerformed
        new Logout().setVisible(true);
    }//GEN-LAST:event_LogoutMenuActionPerformed

    private void paySalaryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paySalaryMenuActionPerformed
        PaySalary paySalary1 = new PaySalary();
        System.gc();
        paySalary1.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(paySalary1);
        dataPanel.repaint();
    }//GEN-LAST:event_paySalaryMenuActionPerformed

    private void viewPayedSalaryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPayedSalaryMenuActionPerformed
        PayedSalary payedSalary = new PayedSalary();
        System.gc();
        payedSalary.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(payedSalary);
        dataPanel.repaint();
    }//GEN-LAST:event_viewPayedSalaryMenuActionPerformed

    private void configureSalaryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureSalaryMenuActionPerformed
        ConfigureSalary configureSalary = new ConfigureSalary();
        System.gc();
        configureSalary.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(configureSalary);
        dataPanel.repaint();
    }//GEN-LAST:event_configureSalaryMenuActionPerformed

    private void addUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserMenuActionPerformed
        UserConfigurations userConfigurations = new UserConfigurations();
        System.gc();
        userConfigurations.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(userConfigurations);
        dataPanel.repaint();
    }//GEN-LAST:event_addUserMenuActionPerformed

    private void userPasswordChangeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordChangeMenuActionPerformed
        UpdateUserConfiguration updateUserConfiguration = new UpdateUserConfiguration();
        System.gc();
        updateUserConfiguration.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(updateUserConfiguration);
        dataPanel.repaint();

    }//GEN-LAST:event_userPasswordChangeMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewAllEmployee viewAllEmployee = new ViewAllEmployee();
        System.gc();
        viewAllEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(viewAllEmployee);
        dataPanel.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        BankReport1Emp bankReport1Emp = new BankReport1Emp();
        System.gc();
        bankReport1Emp.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(bankReport1Emp);
        dataPanel.repaint();

//        try {
//            JasperReport jr = JasperCompileManager.compileReport("./src/sec/anchor/reports/BankReport.jrxml");
//            Map<String, Object> paras = new HashMap<>();
//            JasperPrint jasperPrint;
//            try {
//                jasperPrint = JasperFillManager.fillReport(jr, paras, DBConnection.getInstance().getConnection());
//                JasperViewer.viewReport(jasperPrint, false);
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
//        } catch (JRException ex) {
//            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed

        CentralBankReport bankReport = new CentralBankReport();
        System.gc();
        bankReport.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(bankReport);
        dataPanel.repaint();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        TotalPayed totalPayed = new TotalPayed();
        System.gc();
        totalPayed.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(totalPayed);
        dataPanel.repaint();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void restoreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreMenuActionPerformed
        new BackupRestore(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_restoreMenuActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        new AboutDeveloper(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new HelpMenu(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void removeEmployeeMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeMenu1ActionPerformed
        ViewAllEmployee viewAllEmployee = new ViewAllEmployee();
        System.gc();
        viewAllEmployee.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(viewAllEmployee);
        dataPanel.repaint();
    }//GEN-LAST:event_removeEmployeeMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LogoutMenu;
    private javax.swing.JMenuItem addNewEmployeeMenu;
    private javax.swing.JMenuItem addUserMenu;
    private javax.swing.JMenuItem backUpMenu;
    private javax.swing.JMenuItem configureSalaryMenu;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel dateText;
    private javax.swing.JMenu employeeMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXCollapsiblePane jXCollapsiblePane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private javax.swing.JButton newEmployeeButton;
    private javax.swing.JButton paySalary;
    private javax.swing.JMenuItem paySalaryMenu;
    private javax.swing.JMenuItem removeEmployeeMenu;
    private javax.swing.JMenuItem removeEmployeeMenu1;
    private javax.swing.JMenuItem restoreMenu;
    private javax.swing.JMenu salaryConfigMenu;
    private javax.swing.JLabel timeText;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JMenuItem updateEmployeeMenu;
    private javax.swing.JMenuItem userPasswordChangeMenu;
    private javax.swing.JButton viewPayedButton;
    private javax.swing.JMenuItem viewPayedSalaryMenu;
    // End of variables declaration//GEN-END:variables
private void payView() {
        PaySalary ps = new PaySalary();
        System.gc();
        ps.setSize(dataPanel.getSize());
        dataPanel.removeAll();
        dataPanel.add(ps);
        dataPanel.repaint();
    }

}
