/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sec.anchor.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import sec.anchor.controller.EmployeeController;
import sec.anchor.model.Employee;

/**
 *
 * @author Miyuru Madusanka
 */
public class UpdateEmployee extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    public UpdateEmployee() {
        initComponents();
        try {
            initComponents();
            AutoCompleteDecorator.decorate(nicCombo);
            AutoCompleteDecorator.decorate(bankCombo);
            fillNicComboBox();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(sec.anchor.view.UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        epfNoText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        etfNoText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        accText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nicCombo = new org.jdesktop.swingx.JXComboBox();
        addressText = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dobText = new javax.swing.JTextField();
        bankCombo = new org.jdesktop.swingx.JXComboBox();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        setPreferredSize(new java.awt.Dimension(1024, 568));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        epfNoText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel5.setText("Birthday:");

        contactText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactTextKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel9.setText("Age:");

        etfNoText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel6.setText("Contact No:");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel2.setText("NIC Number:");

        ageText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        accText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accTextKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel7.setText("Bank name:");

        jLabel11.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel11.setText("ETF No:");

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel8.setText("Bank Acc. No:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel3.setText("Name:");

        nameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        nicCombo.setEditable(true);
        nicCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nicComboItemStateChanged(evt);
            }
        });
        nicCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicComboFocusLost(evt);
            }
        });
        nicCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicComboActionPerformed(evt);
            }
        });
        nicCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicComboKeyReleased(evt);
            }
        });

        addressText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel10.setText("EPF No:");

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel4.setText("Address:");

        dobText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bankCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bank Of Ceylon", "Peoples' Bank", "Commercial Bank" }));

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(epfNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bankCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contactText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etfNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bankCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(accText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(epfNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(etfNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed

    }//GEN-LAST:event_nameTextActionPerformed

    private void nicComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nicComboItemStateChanged

    }//GEN-LAST:event_nicComboItemStateChanged

    private void nicComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicComboFocusLost

    }//GEN-LAST:event_nicComboFocusLost

    private void nicComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicComboActionPerformed
        searchEmp();
    }//GEN-LAST:event_nicComboActionPerformed

    private void nicComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicComboKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicComboKeyPressed

    private void nicComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicComboKeyReleased

    }//GEN-LAST:event_nicComboKeyReleased

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String[] nic = (nicCombo.getSelectedItem() + "").split("-");
        int res;
        try {
            res = EmployeeController.deleteEmployee(nic[nic.length - 1]);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Employee Deleted " + nic[nic.length - 1]);
                emptyFields();
                fillNicComboBox();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Delete the Employee " + nic[nic.length - 1]);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot Delete the Customer " + nic, "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String[] nic = (nicCombo.getSelectedItem() + "").split("-");
        Employee employee = new Employee(nic[nic.length - 1], nameText.getText(), addressText.getText(), dobText.getText(), Integer.parseInt(ageText.getText()),
                Integer.parseInt(contactText.getText()), bankCombo.getSelectedItem() + "", accText.getText(), null, epfNoText.getText(), etfNoText.getText());
        try {
            int res = EmployeeController.updateEmployee(employee);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Employee Updated");
                emptyFields();
                fillNicComboBox();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Execute update", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void contactTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTextKeyReleased
        String txt = contactText.getText();
        int caretPosition = contactText.getCaretPosition();
        if (!txt.matches("^[0-9]{0,10}$")) {
            contactText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            contactText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_contactTextKeyReleased

    private void accTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accTextKeyReleased
        String txt = accText.getText();
        int caretPosition = accText.getCaretPosition();
        if (!txt.matches("^[0-9]{0,20}$")) {
            accText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            accText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_accTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accText;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField ageText;
    private org.jdesktop.swingx.JXComboBox bankCombo;
    private javax.swing.JTextField contactText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dobText;
    private javax.swing.JTextField epfNoText;
    private javax.swing.JTextField etfNoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameText;
    private org.jdesktop.swingx.JXComboBox nicCombo;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
  private void emptyFields() {
        nameText.setText(null);
        addressText.setText(null);
        dobText.setText(null);
        ageText.setText(null);
        contactText.setText(null);
        bankCombo.setSelectedItem(null);
        accText.setText(null);
        epfNoText.setText(null);
        etfNoText.setText(null);
    }

    private void searchEmp() {
        if (nicCombo.getSelectedItem() != null) {
            try {
                String[] nic = (nicCombo.getSelectedItem() + "").split("-");
                sec.anchor.model.Employee employee = EmployeeController.searchEmployee(nic[nic.length - 1]);
                if (employee != null) {
                    nameText.setText(employee.getName());
                    addressText.setText(employee.getAddress());
                    dobText.setText(employee.getDob());
                    ageText.setText(employee.getAge() + "");
                    contactText.setText(employee.getContactno() + "");
                    bankCombo.setSelectedItem(employee.getBank());
                    accText.setText(employee.getBankAccNo() + "");
                    epfNoText.setText(employee.getEpfno());
                    etfNoText.setText(employee.getEtfno());
                } else {
                    // JOptionPane.showMessageDialog(this, "No Employee Found! Please add new one");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void fillNicComboBox() throws ClassNotFoundException, SQLException {
        ArrayList<sec.anchor.model.Employee> employees = EmployeeController.loadNicCombo();
        nicCombo.removeAllItems();
        for (sec.anchor.model.Employee e : employees) {
            nicCombo.addItem(e);
        }
    }

}
