/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sec.anchor.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import sec.anchor.controller.UserController;
import sec.anchor.model.User;

/**
 *
 * @author Miyuru Madusanka
 */
public class UpdateUserConfiguration extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    String oldUserName;
    static int val = 0;
    String[] nic;

    public UpdateUserConfiguration() {
        try {
            initComponents();
            fillNicComboBox();
            AutoCompleteDecorator.decorate(nicCombo);
            oldUserName = userNameText.getText();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdateUserConfiguration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        descCombo = new org.jdesktop.swingx.JXComboBox();
        nameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        rePasswordText = new javax.swing.JPasswordField();
        passwordVerification = new javax.swing.JLabel();
        nicCombo = new org.jdesktop.swingx.JXComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        setPreferredSize(new java.awt.Dimension(1024, 568));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel2.setText("NIC Number:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel4.setText("User Name:");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel6.setText("Re-Enter Password:");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel7.setText("E-mail:");

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel8.setText("Designation");

        descCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Assistant manager", "Accountant" }));

        passwordVerification.setForeground(new java.awt.Color(255, 0, 0));

        nicCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(descCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameText)
                                    .addComponent(emailText)
                                    .addComponent(userNameText)
                                    .addComponent(passwordText)
                                    .addComponent(rePasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nicCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(passwordVerification, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(descCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rePasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordVerification))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addGap(0, 156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (new String(passwordText.getPassword()).equals(new String(rePasswordText.getPassword()))) {
            passwordVerification.setText("");
            nic = (nicCombo.getSelectedItem() + "").split("-");
            new AskPassword(null, true, oldUserName).setVisible(true);
            if (val <= 0) {
                updateUser();
            }

        } else {
            passwordVerification.setText("Password & Re-enter password mismatch");
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        passwordVerification.setText("");
        nic = (nicCombo.getSelectedItem() + "").split("-");
        new AskPassword(null, true, oldUserName).setVisible(true);
        if (val <= 0) {
            deleteUser();
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void nicComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicComboActionPerformed
        searchUser();
    }//GEN-LAST:event_nicComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private org.jdesktop.swingx.JXComboBox descCombo;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameText;
    private org.jdesktop.swingx.JXComboBox nicCombo;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel passwordVerification;
    private javax.swing.JPasswordField rePasswordText;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
public void emptyfields() {
        nameText.setText(null);
        emailText.setText(null);
        userNameText.setText(null);
        passwordText.setText(null);
        rePasswordText.setText(null);
    }

    private void searchUser() {
        if (nicCombo.getSelectedItem() != null) {
            try {
                String[] nic = (nicCombo.getSelectedItem() + "").split("-");
                User searchUser = UserController.searchUser(nic[nic.length - 1]);
                if (searchUser != null) {
                    nameText.setText(searchUser.getName());
                    descCombo.setSelectedItem(searchUser.getDesignation());
                    emailText.setText(searchUser.getEmail());
                    userNameText.setText(searchUser.getUsername());

                } else {
                    // JOptionPane.showMessageDialog(this, "No Employee Found! Please add new one");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void fillNicComboBox() throws ClassNotFoundException, SQLException {
        ArrayList<User> user = UserController.loadNicCombo();
        nicCombo.removeAllItems();
        for (User user1 : user) {
            nicCombo.addItem(user1);
        }
    }

    private void updateUser() {
        try {
            User user = new User(nameText.getText(), descCombo.getSelectedItem() + "", nic[nic.length - 1], emailText.getText(), userNameText.getText(), new String(passwordText.getPassword()));
            int res = UserController.updateUser(user);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "User Account Updated");
                emptyfields();
                val = 0;
                fillNicComboBox();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot update Account", "Error", JOptionPane.ERROR_MESSAGE);
                val = 0;
                System.out.println(val);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdateUserConfiguration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void deleteUser() {
        try {
            int res = UserController.deleteUser(nic[nic.length - 1]);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "User Account Removed");
                emptyfields();
                fillNicComboBox();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Remove Account", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdateUserConfiguration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
